### ISSUE TITLE
Asynchronous support

### ISSUE THREAD

**Issue by DamianMel** [jrobichaud/django-structlog#179]
Hi!
Have you considered updating to add asynchronous support like mentioned here: 
https://docs.djangoproject.com/en/4.1/topics/http/middleware/#asynchronous-support

I started some work, but I'm not sure if this would be good direction: https://github.com/DamianMel/django-structlog/blob/feature/make_RequestMiddleware_middleware_both_sync_and_async/django_structlog/middlewares/request.py#L181 (replacing accessing from class to function.)

What do you think?

**Comment by jrobichaud** [comment]
Thanks @DamianMel , I see how to implement it. I'll work on it.

Do you mind if I ask you to review my PR when am done?

**Comment by jrobichaud** [comment]
@DamianMel  #180 is available for review.

**Comment by DamianMel** [comment]
@jrobichaud sure. I will check it and write comments if I will find something worth mentioning. It should take me < 24h from now.

**Comment by DamianMel** [comment]
@jrobichaud I read proposed updated and it looks nice :+1: 
I also tested manually if context is preserved correctly (request_id) and it looks good.
I believe you could merge.

**Comment by jrobichaud** [comment]
@DamianMel , 4.1.0 is out with the change.

Have a great day.

**Comment by jrobichaud** [comment]
@DamianMel I rolled back the change in 4.1.1 but I made available a replacement see [django_structlog.middlewares.request_middleware_router](https://django-structlog.readthedocs.io/en/latest/api_documentation.html#django_structlog.middlewares.request_middleware_router)
