### ISSUE TITLE
Backwards incompatible change in 4.1.0

### ISSUE THREAD

**Issue by gvangool** [jrobichaud/django-structlog#183]
We have a custom `RequestMiddleware` that is inheriting from `django_structlog.middlewares.RequestMiddleware`, with the introduction of async support in #180 that became a function instead of a class.

At that point, tests started to fail with a `TypeError`.
```
TypeError: function() argument 'code' must be code, not str
```

If anyone else runs into it, you can make the following change.
```diff
diff --git c/./middleware.py i/./middleware.py
index 40d563a5..3b5cc81b 100644
--- c/./middleware.py
+++ i/./middleware.py
@@ -1,8 +1,8 @@
 import structlog
-from django_structlog.middlewares import RequestMiddleware
+from django_structlog.middlewares.request import SyncRequestMiddleware


-class LogRequestMiddleware(RequestMiddleware):
+class LogRequestMiddleware(SyncRequestMiddleware):
     def process_view(self, request, view_func, view_args, view_kwargs):
         resolver_match = request.resolver_match
         view_func_qualname = (
```

Can we flag the 4.1.0 release as having backwards-incompatible changes?

**Comment by jrobichaud** [comment]
It is something that `django-structlog` is not currently supporting since I was not aware of people doing this.

Could you explain what you are doing so I could refactor accordingly?

Your change does not allow Async support, I'd like an elegant solution that will allow everything to work.

**Comment by jrobichaud** [comment]
Have you considered using the signal?

https://django-structlog.readthedocs.io/en/latest/api_documentation.html#django_structlog.signals.bind_extra_request_metadata

**Comment by jrobichaud** [comment]
@gvangool, like you suggested I added a note in `4.1`'s changelog. 

https://django-structlog.readthedocs.io/en/latest/changelog.html#february-4th-2023

In your case, I have the feeling you can do like the example from the documentation:

```python
from django.dispatch import receiver
from django_structlog import signals
import structlog

@receiver(signals.bind_extra_request_metadata)
def bind_awesome_stuff(request, logger, **kwargs):
    # Add your code using the request 
    # url_name: the resolved URL name
    # func: the view function (as an import path)
    # project_id: a URL kwarg that is available on 50% of our views
    structlog.contextvars.bind_contextvars(
        url_name="?",
        func="?",
        project_id="?",
    )
```

**Comment by jrobichaud** [comment]
I rolled back the changes in 4.1.1. you can switch back to `RequestMiddleware` if you want.  

`SyncRequestMiddleware` is still available.
