### ISSUE TITLE
Release for 1.1.4 does not contain any middlewares

### ISSUE THREAD

**Issue by jarshwah** [jrobichaud/django-structlog#2]
Hi!

Super keen to use this package, especially for the celery integration. Unfortunately, installing v1.1.4 does not contain the middlewares module. I think the build/deploy has failed in some way.

Here's the output from listing the package contents within a container. Same results for on my host OS.

```
/usr/local/lib/python3.6/site-packages/django_structlog$ ls -la
total 36
drwxr-sr-x 3 root staff  4096 May  8 02:09 .
drwxr-sr-x 1 root staff 16384 May  8 02:09 ..
-rw-r--r-- 1 root staff   274 May  8 02:09 __init__.py
drwxr-sr-x 2 root staff  4096 May  8 02:09 __pycache__
-rw-r--r-- 1 root staff   106 May  8 02:09 apps.py
-rw-r--r-- 1 root staff   453 May  8 02:09 signals.py
django@46b81cdbac10:/usr/local/lib/python3.6/site-packages/django_structlog$ find
.
./__init__.py
./apps.py
./__pycache__
./__pycache__/signals.cpython-36.pyc
./__pycache__/apps.cpython-36.pyc
./__pycache__/__init__.cpython-36.pyc
./signals.py
```

**Comment by jrobichaud** [comment]
I am looking into this right now.

**Comment by jarshwah** [comment]
FWIW I vendored the current state of the project and followed the setup instructions and copied the celery setup from the example project and it's working extremely well. The only thing missing (except for the publish tasks we're discussing in the other thread) is the task name, but I'm not sure if you'd want to bind that by default.

This works for me though:

```python
@receiver(bind_extra_task_metadata)
def receiver_bind_extra_request_metadata(sender, signal, task=None, logger=None, **kwargs):
    logger.bind(task_name=task.name)
```

**Comment by jrobichaud** [comment]
1.1.5 will be out in a few minutes.

**Comment by jrobichaud** [comment]
1.1.5 is available.

**Comment by jrobichaud** [comment]
I will add task_name when the task is enqueued.

You are free to open a new issue to discuss about adding 
`logger.bind(task_name=task.name)` by default if you think it is important.

**Comment by jrobichaud** [comment]
This task_name at enqueue will be in 1.1.6 anytime soon.
