### ISSUE TITLE
Exceptions aren't logged anymore

### ISSUE THREAD

**Issue by ntap-fge** [jrobichaud/django-structlog#226]
Since version 5.0 `RequestMiddleware` doesn't log exceptions anymore (tested with Django 3.2, Python 3.9).

The `request_failed` event seems to have been completely removed and the regular `request_finished` also doesn't contain the exception.

**Comment by jrobichaud** [comment]
I'll have to investigate, but I am unavailable this week. Please stick to an earlier version in the  meantime.

I could not trigger exceptions at all and it appeared to be dead code from an old refactor. I'll have to take a second look.

Just to be sure, you are configured as the documentation and did not create a custom class inheriting from RequestMiddleware?

**Comment by ntap-fge** [comment]
Yes, I'm using `'django_structlog.middlewares.RequestMiddleware'` as the middleware.

Previously Django called the middleware hook `process_exception()` which has been removed in 14da9d8fe2b83b9d05987307dfd67ad00a1f0d33

**Comment by jrobichaud** [comment]
The removal was a dumb mistake, I am putting everything back. 

However, I have to make sure the  middleware is stateless in order to work properly with async. The instance is shared between concurrent requests. 

I'll store the ˋ_raised_exception` flag on the request instead.

**Comment by jrobichaud** [comment]
@ntap-fge the fix is 5.0.2 that was just released, let me know if you have any problems. Thanks.

**Comment by ntap-fge** [comment]
Can confirm that 5.0.2 works fine. Thanks for the quick fix and maintaining django-structlog in general!
