### ISSUE TITLE
`get_x_request_id` from #22

### ISSUE THREAD

**Issue by keyz182** [jrobichaud/django-structlog#25]
We have a request ID on our request already (not in a header), so we're looking at using the support added in #22 .

Is there a reason that `get_x_request_id` is outside the class? It means that in order to override that behaviour, we have to subclass the middleware and completely copy `__call__` to modify the one line, rather than subclass and change just `get_x_request_id`. Happy to do a PR to change it if there's no reason otherwise. 

Another option if that's not appropriate, would be to grab the `get_request_id` func from a setting, and default to the current one.

**Comment by jrobichaud** [comment]
https://django-structlog.readthedocs.io/en/latest/getting_started.html#extending-request-log-metadata

Have you considered overriding the request_id with a second bind?

**Comment by keyz182** [comment]
> https://django-structlog.readthedocs.io/en/latest/getting_started.html#extending-request-log-metadata
> 
> Have you considered overriding the request_id with a second bind?

Yup, that looks good - clearly I didn't RTFM properly :)

**Comment by jrobichaud** [comment]
Let me know if you have any other problems using the library.

I'll leave the issue opened until I add a note in the documentation. It is not clear values can be overridden.
