### ISSUE TITLE
user_id not set properly when using log.bind(user_id=33)

### ISSUE THREAD

**Issue by adrenaline681** [jrobichaud/django-structlog#259]
In my code I'm using bind() to add the user_id to my log line because since its a LoginView the user is not authenticated in the request.

If I pass the user_id using the bind method the log shows up as  `user_id: None`
```
log = logger.bind(method='google')
log.bind(user_id=33)
log.info('user_login')
```

But if I pass it directly to the info method then my log line shows the id properly `user_id: 33`
```
log = logger.bind(method='google')
log.info('user_login', user_id=33)
```

**Comment by jrobichaud** [comment]
Did you try with this?

https://www.structlog.org/en/stable/api.html#structlog.contextvars.bind_contextvars

**Comment by jrobichaud** [comment]
Starting from django-structlog 3.0  you should no longer use logger.bind. See https://django-structlog.readthedocs.io/en/latest/upgrade_guide.html

"Upgrading to 3.0+"

**Comment by adrenaline681** [comment]
Why do you say we should not longer use logger.bind(), its in the first page of the official documentation of structlog:
https://www.structlog.org/en/stable/why.html#data-binding

**Comment by jrobichaud** [comment]
I'll investigate, maybe something is missing in the configuration.

**Comment by jrobichaud** [comment]
In your log, does `method=google` appear?

If so try:

```python
log = logger.bind(method='google')
log = log.bind(user_id=33)
log.info('user_login')
```

**Comment by adrenaline681** [comment]
Yes, method=google appears in both examples i explained,

On the first example I showed (and the one you suggested), user_id=33 doesn't show in the logs
But if I add the user_id argument to the info() method directly it does show up properly.

**Comment by jrobichaud** [comment]
So this should work:

```python
log = logger.bind(method='google')
log = log.bind(user_id=33)
log.info('user_login')
```

**Comment by jrobichaud** [comment]
However, if you want the "user_id" to be available to "request_finished", you need to use [bind_contextvars](https://www.structlog.org/en/stable/api.html#structlog.contextvars.bind_contextvars) instead.

**Comment by adrenaline681** [comment]
I tried this outside of the GoogleLoginView and it works properly:

```
log = logger.bind(method='google')
log = log.bind(user_id=33)
log.info('user_login')
```

But when I use it inside my GoogleLoginView is not working. This is a simplified version of the view but the issue still remains.

```
class GoogleLoginView(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter

    def post(self, request, *args, **kwargs):
        """ Extend the default post method to add logging """
        res = super().post(request, *args, **kwargs)
        log = logger.bind(method='google')
        log.bind(user_id=33)
        log.info('user_login')
        return res
```

This is the log output:

`2023-06-23T16:46:05.932143738Z 2023-06-23T16:46:05.931730Z [info     ] user_login                     [apps.accounts.views] ip=172.18.0.1 method=google request_id=0828aa11-62e7-4a9e-8d56-d2ceb94d009f user_id=None
`

**Comment by jrobichaud** [comment]
the function `.bind` returns another logger so you need to store it in another variable

```python
class GoogleLoginView(SocialLoginView):
    adapter_class = GoogleOAuth2Adapter

    def post(self, request, *args, **kwargs):
        """ Extend the default post method to add logging """
        res = super().post(request, *args, **kwargs)
        log = logger.bind(method='google')
		# log.bind(user_id=33) # <-- NOT like this
        log = log.bind(user_id=33) # <-- like this
        log.info('user_login')
        return res
```

**Comment by jrobichaud** [comment]
Like I said, I would recommend to use this instead:

```
structlog.contextvars.bind_contextvars(method="google", user_id=33)
```

This way  `django-structlog`'s `"request_finished"` log would also have the metadata.

**Comment by jrobichaud** [comment]
I really don't mind to help, it helps me understand people's use cases. 

Sometimes it ends up in documentation improvements or new features.
