### ISSUE TITLE
Receiver code breaks if headers is None

### ISSUE THREAD

**Issue by prik2693** [jrobichaud/django-structlog#26]
Not sure how to pass the params to the receiver_after_task_publish method.

File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 461, in delay
    return self.apply_async(args, kwargs)
  File "/usr/local/lib/python3.6/site-packages/celery/app/task.py", line 573, in apply_async
    **dict(self._get_exec_options(), **options)
  File "/usr/local/lib/python3.6/site-packages/celery/app/base.py", line 354, in send_task
    reply_to=reply_to or self.oid, **options
  File "/usr/local/lib/python3.6/site-packages/celery/app/amqp.py", line 315, in publish_task
    exchange=exchange, routing_key=routing_key)
  File "/usr/local/lib/python3.6/site-packages/celery/utils/dispatch/signal.py", line 166, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/django_structlog/celery/receivers.py", line 20, in receiver_after_task_publish
    "task_enqueued", child_task_id=headers["id"], child_task_name=headers["task"]
TypeError: 'NoneType' object is not subscriptable

**Comment by jrobichaud** [comment]
Can you give more detail on your celery configuration and how to reproduce the problem.

I never seen this problem.

**Comment by prik2693** [comment]
Got the issue!
I am running on celery 3.1.25, headers is not there as a param in the older versions of after_task_publish event, task id comes in body(doc link - http://docs.celeryproject.org/en/2.4/userguide/signals.html#after-task-publish
) and hence the error.

**Comment by jrobichaud** [comment]
Celery 3 is not currently supported.

I will try to see what it needs to support it

**Comment by jrobichaud** [comment]
@prik2693 I did some tests with older celery version but celery worker exits with status 0 when starting a task with 3.1.26. I have a similar behaviour with 4.0.2 but it is with status 1.

Unless there is a big demand or you or other people are willing to support 3.X, I am going to set the minimum supported celery version from 4.1 and higher. This until there are clear guidelines on celery release cycles (See: https://github.com/celery/celery/issues/4957)

You can checkout this branch (https://github.com/jrobichaud/django-structlog/pull/28) if you want to give it a try.

**Comment by prik2693** [comment]
Checked your PR, tested it out too, seems to be working fine, can we add support for it? celery 4 has some features missing so cant really upgrade my application.

**Comment by jrobichaud** [comment]
If you consider using the library I am sure we can manage something out.

I would really like the demo to work in version 3.X, so if you can help me make it work I have no problem support 3.X.

The current issue is when a task is enqueued Celery worker just stops.

What do you think?

**Comment by chiragjn** [comment]
Hey @jrobichaud, apparently `kombu<4` has problems with Redis 3.x, I tried this branch with `redis<3` and Redis 2.8.19 and was able to get the demo project working correctly

**Comment by jrobichaud** [comment]
Fixed in 1.5.0 that is released on pypi:

https://pypi.org/project/django-structlog/

Thanks @chiragjn for pointing out what was causing the crash.
