### ISSUE TITLE
Does django-structlog has compatibility with Celery Beat?

### ISSUE THREAD

**Issue by adrenaline681** [jrobichaud/django-structlog#260]
I've configured django-structlog to work with Celery by following the documentation, but I noticed that my Celery Beat worker doesn't produce any logs whenever it sends a new task or if the schedule was changed in the admin panel.

Can django-structlog also log these events from Celery Beat?

**Comment by jrobichaud** [comment]
In the demo project there is a task scheduled with beat. I know the logs in the task will work properly.

I am not sure if there are logs when a task starts and finish.

You can try yourself, ill take a look next week.

**Comment by adrenaline681** [comment]
The task logs work fine:

For example this is an example task:

```
@app.task(bind=True)
def debug_task(self, x, y):
    time.sleep(5)
    logger.info('task_debug', x=x, y=y)
    return f'Result of {x} + {y} = {x + y}'
```

And my celery worker outputs this:

```
{"event": "task_debug", "x": 2, "y": 5, "task_id": "5f60c3ff-4938-4975-b9a3-7833e3fae7ae", "timestamp": "2023-06-24T04:39:06.550902Z", "logger": "main.celery", "level": "info"}

{"event": "task_succeeded", "task_id": "5f60c3ff-4938-4975-b9a3-7833e3fae7ae", "timestamp": "2023-06-24T04:39:06.561757Z", "logger": "django_structlog.celery.receivers", "level": "info"}
```

But inside my Celery Beat logs I only see this, and nothing shows up after, even when scheduled tasks are being sent:

```
celery beat v5.3.0 (emerald-rush) is starting.
2023-06-24T02:05:44.970689253Z LocalTime -> 2023-06-23 19:05:44
2023-06-24T02:05:44.970697418Z Configuration ->
2023-06-24T02:05:44.970700314Z     . broker -> sqs://localhost//
2023-06-24T02:05:44.970717846Z     . loader -> celery.loaders.app.AppLoader
2023-06-24T02:05:44.970720431Z     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
2023-06-24T02:05:44.970724739Z     . logfile -> [stderr]@%INFO
2023-06-24T02:05:44.970727013Z     . maxinterval -> 5.00 seconds (5s)
```

Normally inside my Celery Beat logs I see lines for when a task is sent, or when it detects a change in the schedule. They look something like this:

`2023-06-23 08:00:00,100 INFO beat: Scheduler: Sending due task email_reminder (email_reminder_task)`

**Comment by adrenaline681** [comment]
Not sure if this helps but I found this, if I add the "celery" logger to my Celery logging config:

```
  'loggers': {
           'django_structlog': {
               'handlers': ['console'],
               'level': 'INFO',
           },
           'myProject': {
               'handlers': ['console'],
               'level': 'INFO',
           },
           'celery': {
               'handlers': ['console'],
               'level': 'INFO',
           }
       }
```

Then I start seeing a lot more information in my logs, in both my Celery worker logs and my Celery Beat logs
The issue is that these logs are not formatted properly.


**Celery Worker Logs:** 

Now I see the "task received" log but is not formatted properly like the "task_succeeded" log. 

For each task executed, I see these 4 log lines:
```
{"event": "Task main.celery.debug_task[642eaaeb-b3b9-4e89-8928-4278cf57078e] received"}

{"event": "task_debug", "x": 2, "y": 5, "task_id": "642eaaeb-b3b9-4e89-8928-4278cf57078e", "timestamp": "2023-06-24T04:56:33.167747Z", "logger": "main.celery", "level": "info"}

{"event": "task_succeeded", "task_id": "642eaaeb-b3b9-4e89-8928-4278cf57078e", "timestamp": "2023-06-24T04:56:33.176587Z", "logger": "django_structlog.celery.receivers", "level": "info"}

{"event": "Task main.celery.debug_task[642eaaeb-b3b9-4e89-8928-4278cf57078e] succeeded in 5.009107018995564s: 'Result of 2 + 5 = 7'"}
```
As you can see lines 1 and 4 are not formatted properly in JSON, I think line 1 should look something like this:  
`{"event": "task_received", etc.... }`


**Celery Beat Logs:** 

Now if I look at the Celery Beat logs I see this:

```
LocalTime -> 2023-06-23 21:55:26
2023-06-24T04:55:26.533208605Z Configuration ->
2023-06-24T04:55:26.533211521Z     . broker -> sqs://localhost//
2023-06-24T04:55:26.533214106Z     . loader -> celery.loaders.app.AppLoader
2023-06-24T04:55:26.533216610Z     . scheduler -> django_celery_beat.schedulers.DatabaseScheduler
2023-06-24T04:55:26.533222371Z     . logfile -> [stderr]@%INFO
2023-06-24T04:55:26.533225026Z     . maxinterval -> 5.00 seconds (5s)
2023-06-24T04:55:26.534266794Z {"event": "beat: Starting..."}
2023-06-24T04:55:28.261677564Z {"event": "Scheduler: Sending due task Debug (main.celery.debug_task)"}
2023-06-24T04:55:43.114375911Z {"event": "Scheduler: Sending due task Debug (main.celery.debug_task)"}
2023-06-24T04:55:58.114250666Z {"event": "Scheduler: Sending due task Debug (main.celery.debug_task)"}
```

As you can see now I do see the "Sending due task" logs but they don't seem to be formatted properly in JSON either.

I think it would be great if celery worker could have log events similar to django requests :
```
1. request_started
2. custom_logs
3. request_finished
```

So would look like this:
```
1. task_received
2. custom logs
3. task_succeeded / task_failed
```

You could also have an extra event for the results of the task that includes the time that it took to run:

`{"event": "task_result", "elapsed_time": 5.0095464, result: "Result of 2 + 5 = 7" }`

This is all information that celery normally outputs in its logs, so I think should be included in structlogs. 

Please let me know your thoughts about this.

**Comment by jrobichaud** [comment]
You can do it yourself if you register this signal:

```python
from django_structlog.celery import signals
@receiver(signals.bind_extra_task_metadata)
def receiver_bind_extra_request_metadata(sender, signal, task=None, logger=None, **kwargs):
    logger = structlog.getLogger("django_structlog.celery.receivers")
    logger.info("task_received")
```

this will do this:
![image](https://github.com/jrobichaud/django-structlog/assets/12142702/c6eea12a-fefa-4698-8ca1-7c6e2847dbce)

**Comment by jrobichaud** [comment]
or in `django_structlog/celery/receivers.py`

we could add this line:
![image](https://github.com/jrobichaud/django-structlog/assets/12142702/755d1862-dbd6-4d8e-a5fa-35c39d0a331a)

**Comment by adrenaline681** [comment]
I think makes more sense if it comes by default to keep consistency with how regular requests get logged (request_started / request_finished)

**Comment by jrobichaud** [comment]
`task_started` or `task_received`?

**Comment by adrenaline681** [comment]
The default logs from celery mention "received" so i think task_received makes more sense in the context of a worker that receives a task from a queue.

**Comment by jrobichaud** [comment]
`received` is the term celery use the broker receive the task.

https://docs.celeryq.dev/en/stable/userguide/signals.html#task-received

Celery use `run` then a task is executing.
https://docs.celeryq.dev/en/stable/userguide/signals.html#task-prerun
https://docs.celeryq.dev/en/stable/userguide/signals.html#task-postrun

I prefer `task_started` because it starts the execution.

**Comment by jrobichaud** [comment]
do you think we should also log the task's name?

Ex:
```
task=django_structlog_demo_project.taskapp.celery.scheduled_task
```

**Comment by adrenaline681** [comment]
Yes, I think it will be very helpful, otherwise is hard to know which task was received/finished

**Comment by adrenaline681** [comment]
Maybe this is more complex but having the time it took for the task to finish in the "task_finished" or "task_error" event would be quite helpful also to monitor that your tasks are not running longer than expected.

**Comment by adrenaline681** [comment]
> `task_started` or `task_received`?

task_started makes sense also, so no issues on my side

**Comment by jrobichaud** [comment]
> Maybe this is more complex but having the time it took for the task to finish in the "task_finished" or "task_error" event would be quite helpful also to monitor that your tasks are not running longer than expected.

Celery does not even provide the task that was being ran in its signal.

https://docs.celeryq.dev/en/v5.3.1/userguide/signals.html#task-success

the `task_success`'s implementation
![image](https://github.com/jrobichaud/django-structlog/assets/12142702/015e4b63-e5b6-48cf-9393-a0bcda6c8f89)

It will be complicated to implement since most of the implementation is stateless (beside structlog's contextvars).

I think we should create a different issue for this one.

**Comment by jrobichaud** [comment]
please take a look at #263

**Comment by jrobichaud** [comment]
@adrenaline681 5.2.0 is out with the fix.

**Comment by adrenaline681** [comment]
> @adrenaline681 5.2.0 is out with the fix.

Awesome, thanks for the quick change!
