### ISSUE TITLE
Structlog logs break when code executes FF3Cypher encryption

### ISSUE THREAD

**Issue by adrenaline681** [jrobichaud/django-structlog#274]
Sorry for messaging again, but I found a very weird bug that has been driving me crazy for the last 5 hours. Finally I was able to narrow it down to a single cause.

To make sure that logs are working properly I created a very simple view with a log inside:
```
class TestView(views.APIView):
    def get(self, request):
        logger.info('testing_log')
        return response.Response('success')
```

If I send a request to the endpoint all the logs look normal:
```
2023-07-25T07:17:03.543525Z [info     ] request_started                [django_structlog.middlewares.request] ip=172.25.0.1 request=GET /testing_view/ request_id=5d10f688-ea7a-4925-8421-e45a438bb2d7 user_agent=PostmanRuntime/7.32.3 user_id=12
2023-07-25T07:17:03.576919Z [info     ] testing_log                    [apps.accounting.views] ip=172.25.0.1 request_id=5d10f688-ea7a-4925-8421-e45a438bb2d7 user_id=12
2023-07-25T07:17:03.582571Z [info     ] request_finished               [django_structlog.middlewares.request] code=200 ip=172.25.0.1 request=GET /testing_view/ request_id=5d10f688-ea7a-4925-8421-e45a438bb2d7 user_id=12
```

But now if I use the "FF3" library to encrypt a string, all the logs break after the encryption happens.
```
from ff3 import FF3Cipher

class TestView(views.APIView):
    def get(self, request):

        # Encrypt a string
        cypher = FF3Cipher('A1B2C3D4E5F67890FEEDCBA987654321', '1A2B3C4D5E7890')
        encrypted_number = cypher.encrypt('000000000001')

        logger.info('testing_log')
        return response.Response('success')
```

After the initial "request_started" log line, I start getting an extra line of unformatted log for each logline I have.  
```
023-07-25T07:24:05.631042Z [info     ] request_started                [django_structlog.middlewares.request] ip=172.25.0.1 request=GET /testing_view/ request_id=b84a2c94-5873-4e10-8cfa-2bb54255dd79 user_agent=PostmanRuntime/7.32.3 user_id=12
2023-07-25T07:24:05.658689Z [info     ] testing_log                    [apps.accounting.views] ip=172.25.0.1 request_id=b84a2c94-5873-4e10-8cfa-2bb54255dd79 user_id=12
INFO:apps.accounting.views:{'event': 'testing_log', 'user_id': 12, 'ip': '172.25.0.1', 'request_id': 'b84a2c94-5873-4e10-8cfa-2bb54255dd79', 'timestamp': '2023-07-25T07:24:05.658689Z', 'logger': 'apps.accounting.views', 'level': 'info'}
2023-07-25T07:24:05.665623Z [info     ] request_finished               [django_structlog.middlewares.request] code=200 ip=172.25.0.1 request=GET /testing_view/ request_id=b84a2c94-5873-4e10-8cfa-2bb54255dd79 user_id=12
INFO:django_structlog.middlewares.request:{'code': 200, 'request': 'GET /testing_view/', 'event': 'request_finished', 'user_id': 12, 'ip': '172.25.0.1', 'request_id': 'b84a2c94-5873-4e10-8cfa-2bb54255dd79', 'timestamp': '2023-07-25T07:24:05.665623Z', 'logger': 'django_structlog.middlewares.request', 'level': 'info'}
```

And this not only happens inside this view. If after I send requests to other endpoints ALL my loglines are now broken.
I can only fix the issue by restarting the Django server.

The bug seems to appear no matter if I use the `JSONRenderer()` or the `ConsoleRenderer()`.

**Comment by jrobichaud** [comment]
You could try narrow it down further with only structlog and FF3 in a simple main.py file.

**Comment by adrenaline681** [comment]
Hello, yes I've tested it right now on the demo App and the same happens there.

I simply added the encryption lines to the scheduled_task and this is how the logs look like (I highlighted in yellow the lines that started to show up)

![logs](https://github.com/jrobichaud/django-structlog/assets/12194431/d7ceb63f-b1b4-41b3-a242-12f36a42246b)

**Comment by adrenaline681** [comment]
Were you able to reproduce it?

**Comment by jrobichaud** [comment]
Haven't tried yet. I might tonight.

Did you try to reproduce with only ff3 and structlog in a main.py?

**Comment by jrobichaud** [comment]
I looked at the source code of ff3 and I found this:

<img width="301" alt="image" src="https://github.com/jrobichaud/django-structlog/assets/12142702/5e2564dc-7fad-4327-ac5a-4a3a10a94493">

I could then reproduce the bug with only with this:
```python
class TestView(views.APIView):
    def get(self, request):
        import logging # <- add this 
        logging.debug("reproduce the bug") # <- and this 
        logger.info('testing_log')
        return response.Response('success')
```


If we look in the source code of [logging.debug()](https://github.com/python/cpython/blob/8d61a71f9c81619e34d4a30b625922ebc83c561b/Lib/logging/__init__.py#L2220-L2221) we find this:

```python
def debug(msg, *args, **kwargs):
    """
    Log a message with severity 'DEBUG' on the root logger. If the logger has
    no handlers, call basicConfig() to add a console handler with a pre-defined
    format.
    """
    if len(root.handlers) == 0:
        basicConfig()
    root.debug(msg, *args, **kwargs)
```

Since in the `loggers` configuration has no `root` longer configuration it loads the `basicConfig()`.

So I could get rid of the problem by replacing this:

```python
"loggers": {
        "django_structlog": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
        "django_structlog_demo_project": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
        "foreign_logger": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
    },
```

By this:

```python
	"loggers": {
        "": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO"
         },
    },
```

I'll have to read about the python logging configuration good practices and decide how I should modify the examples.

@adrenaline681 , now you need to figure out what is the appropriate logging configuration for your project.

**Comment by jrobichaud** [comment]
I am also not sure if ff3 should be using the root logger.

**Comment by jrobichaud** [comment]
@adrenaline681, if you want to disable the root handler, you can register a `logging.NullHandler` handler to the root logger. This way it will not load the basic config.

Like this:

```python

    "handlers": {
        # ...other handlers
        
        # declare no-op handler
        "no-op": {
            "class": "logging.NullHandler",
        }
    },
    "loggers": {

        # assign a no-op handler for the root logger
        "": {
            "handlers": ["no-op"],
            "level": "ERROR",
        },

        # rest of the loggers
        "django_structlog": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
        "django_structlog_demo_project": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
        "foreign_logger": {
            "handlers": ["colored_stream", "flat_line_file", "json_file"],
            "level": "INFO",
        },
```

**Comment by adrenaline681** [comment]
Oh nice, ill give this a try.  I also created an issue in the FF3 package and they said they will fix it.

**Comment by jrobichaud** [comment]
@adrenaline681
I made a PR for [ff3](https://github.com/mysto/python-fpe/pull/34) but your configuration is still subject to have this problem again if you introduce another library doing this.

You should still update your logging configuration accordingly.

**Comment by adrenaline681** [comment]
Yes, I already changed my config. Thanks!
