### ISSUE TITLE
Celery task context - json compatible only ?

### ISSUE THREAD

**Issue by gg-mmill** [jrobichaud/django-structlog#277]
Hello, 
I noticed that when the logging context contains non-json encodable objects (such as a `set`), triggering a celery task raises with `TypeError: Object of type set is not JSON serializable`

For example, the following will raise:
```python
from celery import Celery
app = Celery()

@app.task()
def null_task():
    pass

def launch_null_task():
    with structlog.contextvars.bound_contextvars(
            i_am_a_set={1, 2},
        ):
        null_task.delay()

launch_null_task()
```

This likely comes from the adding of the context to the task headers in 
https://github.com/jrobichaud/django-structlog/blob/25537986e0f69354ce3d7bca371e5795be37c3ec/django_structlog/celery/receivers.py#L21

Is this an expected behaviour ? Is using `modify_context_before_task_publish` the expected way to handle this ?

**Comment by jrobichaud** [comment]
Currently django-structlog works only with json serializable values. 

You should format it to a string for now.

If its not acceptable we could discuss of a solution.

django-structlog has to store the context values in the task. "Pickling" appeared to be overkill to me.

**Comment by jrobichaud** [comment]
I thought of converting any non-primitive to a string but it could result of different logs between the view logs and the task logs depending of the log renderer used.

**Comment by gg-mmill** [comment]
Hello, this is perfectly acceptable, the biggest annoyance was that the bug was quite a bit hard to track down !

I think that clearly stating the issue in the doc would be a good start, and indeed it's not so easy to have a more generic solution, 
esp. since when pickle is used to serialize celery tasks, there wouldn't be problem.

**Comment by jrobichaud** [comment]
If the bound object does not change, I'd recommend most of the time to bind a string of the object rather than the whole object.

1. the object has to be serialized to string with each log
2. the object will need to be pickled when transferred to celery which takes more resources and storage than a string.

If the bound object is changed between logs, it's another story.

**Comment by jrobichaud** [comment]
I fixed the references in the doc.

Here's your new doc in action: https://django-structlog.readthedocs.io/en/latest/celery.html#getting-started-with-celery

**Comment by gg-mmill** [comment]
Thanks for the feedback !
