### ISSUE TITLE
Is there a way of selectively disabling request_starter / request_finished / task_started / task_succeeded / task_enqueued?

### ISSUE THREAD

**Issue by adrenaline681** [jrobichaud/django-structlog#283]
During development, the request_starter / request_finished / task_started / task_succeeded / task_enqueued logs start to clutter the command line. 

Is there a way to selectively disable some of these logs? 

For example: 
- Disable "request_finished" only
- Disable "task_started" and "task_succeeded"
- Disable all except "task_enqueued" (celery beat)

**Comment by jrobichaud** [comment]
Python has a log filtering mechanism. Have you considered it?

**Comment by adrenaline681** [comment]
I've never used it but i will give it a try, thanks

**Comment by jrobichaud** [comment]
`config/settings/my_filters.py` (you might want to use a better file location)
```python
# filters implementations


def event_blacklist(blacklist):
    # this filter remove the events included in the provided blacklist
    b = set(blacklist)
    def func(record):
        return record.msg["event"] not in b

    return func
```

`config/settings/local.py`
```python

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": { # <- declaration of filters
        "event_blacklist": {
            "()" : "config.settings.my_filters.event_blacklist",
            "blacklist": ["task_enqueued"] # <- list of events to blacklist
        }
    },
    "formatters": {
    # ....

    "handlers": {
        "colored_stream": {
            "class": "logging.StreamHandler", 
            "formatter": "colored",
            "filters": ["event_blacklist"], # <- filters to use for this handler
        },
```

Source: https://docs.python.org/3/howto/logging-cookbook.html#custom-handling-of-levels

Do whatever you want with the filter.

**Comment by jrobichaud** [comment]
I was not sure you found a solution since you left the issue opened. 👍
