### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by lewoudar** [jrobichaud/django-structlog#294]
Hello everyone,
following #292, I think it is a good idea to change the default example in the [getting started]() documentation.
It may lead inexperienced developers to a big issue if they just copy/paste the snippet. We should remove file handlers or at least explain the risks of quickly saturating the disk space if we just use the default configuration.

**Comment by jrobichaud** [comment]
@lewoudar , can you take a look at https://github.com/jrobichaud/django-structlog/commit/9f59204313420cb3eaba33807d3d4a61d3812b8a and tell me if it is clean enough?

**Comment by jrobichaud** [comment]
Or simply there: https://github.com/jrobichaud/django-structlog#getting-started

**Comment by lewoudar** [comment]
Hi @jrobichaud ,
the comments look good to me :)

Will they be included in the documentation?

**Comment by jrobichaud** [comment]
The readme is used to generate the documentation. I used sphinx reference inclusion tricks so I do not have to repeat myself.
 [See for yourself](https://django-structlog.readthedocs.io/en/latest/getting_started.html).

However, I really don't want to go into too much details about other librairies or python itself.

**Comment by lewoudar** [comment]
ok, thanks for your responsiveness
