### ISSUE TITLE
[Feature-Request] Send bind_extra_task_metadata after binding task metadata

### ISSUE THREAD

**Issue by chiragjn** [jrobichaud/django-structlog#32]
Right now `bind_extra_task_metadata` is being sent before task metadata from `__django_structlog__` is bound to the logger.

Would it make sense to send it after instead? I know this means the receiver has to be careful with whatever is already bound.

I have a use case where I am trying to unbind some vars bound by django_structlog. This works out perfectly with `bind_extra_request_metadata` as it is sent after django_structlog is done binding whatever it can

If this is acceptable, I can help by sending a PR

**Comment by jrobichaud** [comment]
https://github.com/jrobichaud/django-structlog/blob/204154d9d12b1e3c103cf1fece0c0179e07a3b68/django_structlog/celery/receivers.py#L31-L38

You mean to move line 34-36 at the end?

This is a good idea. It would allow to override values if necessary.

I do not see any issues with this, you can create a PR.

**Comment by jrobichaud** [comment]
Would it be cleaner for your use case to be able to modify metadata directly through a signal?

**Comment by jrobichaud** [comment]
It could be another future change though.

**Comment by chiragjn** [comment]
Opened #33 for this. Adding a new signal can be a feature if you see any use cases for it, but for now, I like the simplicity of one signal per middleware and they both provide enough arguments to cover most cases

**Comment by jrobichaud** [comment]
Fixed in 1.5.1

**Comment by jrobichaud** [comment]
Thanks again.
