### ISSUE TITLE
Possibility to specify custom header name for bounded request_id

### ISSUE THREAD

**Issue by badziyoussef** [jrobichaud/django-structlog#324]
The application could be behind aws elb, that use a non customisable trace_id X-Amzn-Trace-Id, if we can specify request header name from settings, we can use same id generated by aws across all logs. What do you think?

**Comment by jrobichaud** [comment]
can it be achieved using [bind_extra_request_metadata](https://django-structlog.readthedocs.io/en/latest/api_documentation.html#django_structlog.signals.bind_extra_request_metadata) signal?

**Comment by jrobichaud** [comment]
I am not sure if you mean a request header to bind to the logs or return a an ID in a header in the response.

**Comment by badziyoussef** [comment]
> You can technically do this:
> 
> ```python
> from django.contrib.sites.shortcuts import get_current_site
> from django.dispatch import receiver
> from django_structlog import signals
> import structlog
> 
> @receiver(signals.bind_extra_request_metadata)
> def bind_custom_id(request, logger, **kwargs):
>     my_custom_id = "hey"
>     structlog.contextvars.bind_contextvars(request_id=my_custom_id)
> ```

Yes I know, ok I will go with that, thank you.

**Comment by jrobichaud** [comment]
I am considering to add a section "How-To Guides" with these different use-cases I saw over time (#325).
