### ISSUE TITLE
[Feature Request] Custom Arguments to Receivers

### ISSUE THREAD

**Issue by prik2693** [jrobichaud/django-structlog#34]
The celery middleware binds the entire logger context to the tasks currently, this leads to an increase in the message size of the tasks. 
I would like to pass only the request_id to the receivers. 

One of the possible solutions is to make the receivers being connected class methods of the middleware itself. That way one can just inherit and override the class methods. I can raise a PR for it if it's acceptable.

**Comment by jrobichaud** [comment]
1.5.2 should be available with a new signal `modify_context_before_task_publish` that should suit your needs.

https://django-structlog.readthedocs.io/en/latest/celery.html#modify-context-before-task-publish

Ex:

```python
from django.dispatch import receiver
from django_structlog.celery import signals

@receiver(signals.modify_context_before_task_publish)
def receiver_modify_context_before_task_publish(sender, signal, context):
    keys_to_keep = {"request_id", "parent_task_id"}
    new_dict = {key_to_keep: context[key_to_keep] for key_to_keep in keys_to_keep if key_to_keep in context}
    context.clear()
    context.update(new_dict)
```

**Comment by prik2693** [comment]
Wouldnt adding another signal increases an overhead? Don't you think allowing overriding class methods would be a better approach?

**Comment by jrobichaud** [comment]
I am pretty sure a signal with 0 or 1 receiver is fast enough.
