### ISSUE TITLE
Pin django-ipware dependency in pyproject.toml

### ISSUE THREAD

**Issue by mmcclelland1002** [jrobichaud/django-structlog#388]
`django-ipware<=5.0.2`

please pin `django-ipware` in `pyproject.toml`

**Comment by jrobichaud** [comment]
Can you explain what are the breaking changes?

**Comment by jrobichaud** [comment]
You can still pin it in your `requirements.txt`.

**Comment by jrobichaud** [comment]
I am currently releasing 6.0.1 with just this fix.

**Comment by jrobichaud** [comment]
6.0.1 is out with the fix. 

Version 7.X of `django-structlog` will use `django-ipware` 6+.

@mmcclelland1002 please let me know how it affects `django-structlog` users.

**Comment by jrobichaud** [comment]
I'd like to provide an appropriate change log / upgrade guide.

**Comment by jrobichaud** [comment]
Is it because of this?

https://github.com/un33k/django-ipware/pull/108
