### ISSUE TITLE
Bind data to the request finished log event

### ISSUE THREAD

**Issue by prik2693** [jrobichaud/django-structlog#39]
Django Structlog request middleware logs an event ‘request_finished’ when a request ends with 200 status, would like to tmp bind additional parameters to this event log line.

Currently it’s not supported, is there way we can achieve this?

**Comment by jrobichaud** [comment]
I could create a signal pretty much like `bind_extra_request_metadata` that would allow you to do the same but just before the `request_finished` and `request_failed`

Can this do?

`bind_extra_request_metadata`:  https://django-structlog.readthedocs.io/en/latest/getting_started.html#extending-request-log-metadata

**Comment by prik2693** [comment]
Yup, sth like this signal could work.

**Comment by jrobichaud** [comment]
@prik2693, my example are a little poor, only binding the user email. If you could provide me some awesome examples that would be appreciated.
