### ISSUE TITLE
Add support for django-ipware 6.x

### ISSUE THREAD

**Issue by paulschreiber** [jrobichaud/django-structlog#404]
### Description
Add support for django-ipware 6.x. Current version is 6.0.2. django-structlog requires django-ipware < 6.

**Comment by jrobichaud** [comment]
@paulschreiber I am going to release version 7.0.0 later this week with this fix.

You can use `django-structlog` version `6.0.0` which has no limitation on `django-ipware` in the meantime.

Sorry for the trouble.

**Comment by jrobichaud** [comment]
@paulschreiber 7.0.0 is out now.
