### ISSUE TITLE
A way to ignore a specific endpoint

### ISSUE THREAD

**Issue by badziyoussef** [jrobichaud/django-structlog#412]
Sometimes, we have a noisy endpoint that we want just bypass from being  logged by RequestMiddleware, is there a way to do that? I have an endpoint massively called by mobile app that polute my logs.

**Comment by jrobichaud** [comment]
Have you considered using log filters?

https://docs.python.org/3/library/logging.html#filter-objects ?

**Comment by badziyoussef** [comment]
No, I didn't, I will try this, thanks for helping.

**Comment by mohamedTbarka** [comment]
@jrobichaud, can u please give us an exemple how to use log filters to achieve that ?

**Comment by jrobichaud** [comment]
I do not have any example but I would google it.

You might want to look into this too:
https://www.structlog.org/en/stable/processors.html#filtering

**Comment by jrobichaud** [comment]
maybe this could be an inspiration: https://github.com/jrobichaud/django-structlog/issues/283

**Comment by jrobichaud** [comment]
If you manage to do a clean solution, a recipe could be added to the [How-tos of the documentation](https://django-structlog.readthedocs.io/en/latest/how_tos.html).

**Comment by jrobichaud** [comment]
Thanks for your contribution.

https://django-structlog.readthedocs.io/en/latest/how_tos.html#filter-logs-from-being-recorded
