### ISSUE TITLE
ModuleNotFoundError: No module named 'structlog'

### ISSUE THREAD

**Issue by sinjorjob** [jrobichaud/django-structlog#5]
I installed django-structlog with pip according to the procedure, but the following error occurs in import structlog.

<procedure>
pip install django-structlog

<error messages>
>pip install django-structlog
Collecting django-structlog
  Cache entry deserialization failed, entry ignored
  Using cached https://files.pythonhosted.org/packages/38/aa/3c63f5006310795c9220376cbd864ce06d6c36d7d32de8c35aab31699ddf/django_structlog-1.2.2-py3-none-any.whl
Requirement already satisfied: django>=1.11structlog in c:\users\mask\desktop\desktop\knowledge\pdfminer\venv\struct\lib\site-packages (from django-structlog)
Collecting django-ipware (from django-structlog)
Requirement already satisfied: sqlparse in c:\users\mask\desktop\desktop\knowledge\pdfminer\venv\struct\lib\site-packages (from django>=1.11structlog->django-structlog)
Requirement already satisfied: pytz in c:\users\mask\desktop\desktop\knowledge\pdfminer\venv\struct\lib\site-packages (from django>=1.11structlog->django-structlog)
Installing collected packages: django-ipware, django-structlog
Successfully installed django-ipware-2.1.0 django-structlog-1.2.2

>python manage.py shell
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import structlog
Traceback (most recent call last):
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'structlog'
>>>
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
Are there any steps missing?

**Comment by jrobichaud** [comment]
It should have installed structlog has well. Ill look into this. 

In the meantime if you `pip install structlog` does it work?

**Comment by jrobichaud** [comment]
I just spotted the issue, ill fix this soon.
In the meantime the workaround should work.

**Comment by jrobichaud** [comment]
The fix will be in 1.2.3 that will be available in about 10 minutes from now.

**Comment by jrobichaud** [comment]
1.2.3 is out

**Comment by jrobichaud** [comment]
Please reopen the issue if it does not solve the problem you are having.

Thank you for using django-structlog. 

Good day.

**Comment by sinjorjob** [comment]
Thank you for your fast response.
Tt worked fine!
