### ISSUE TITLE
Logs not being output to designated location

### ISSUE THREAD

**Issue by crazyberry7** [jrobichaud/django-structlog#53]
In the docs, the log path is specified as logs/flat_line.log, logs/json.log..etc. After going through installation and adding middleware and defining a custom LOGGING config, no log files matching the log filenames above seem to be created. 

I do see the struct log in the console output:

{'request_id': 'e0550fc9-35dd-4d4a-bf97-b30b406a6123', 'user_id': None, 'ip': '127.0.0.1', 'event': KeyError('username'), 'timestamp': '2020-10-16T21:29:13.300240Z', 'logger': 'api.views.app_endpoints', 'level': 'error'}

Any help would be appreciated.

**Comment by jrobichaud** [comment]
Did you look at the demo project in the repository?
