### ISSUE TITLE
Log encoding issue

### ISSUE THREAD

**Issue by yuanjiushao** [jrobichaud/django-structlog#561]
I saw structlog.processors UnicodeDecoder() defaults to "utf-8", 
but my log output is "msg": "\ u5e8f \ u5217 \ u5316 \ u5b57 \ u6bb5 \ u683c \ u5f0f \ u9a8c \ u8bc1_5931 \ u8d25 \ u3002",
not in Chinese. 
May I ask what the reason is?

**Comment by jrobichaud** [comment]
I see a space between every \ and u, this is not correct utf8.

**Comment by yuanjiushao** [comment]
Sorry, the actual output is as follows:"msg": "\u5e8f\u5217\u5316\u5b57\u6bb5\u683c\u5f0f\u9a8c\u8bc1\u5931\u8d25\u3002"，
In logging Under StreamHandler, Chinese is displayed normally,
In logging. handlers Exception in WatchedFileHandler

**Comment by jrobichaud** [comment]
Could you share your logging configuration of your django settings.py.

- `structlog.configure(...)`
- `LOGGING =...`

**Comment by jrobichaud** [comment]
This Japanese blog post about structlog seems to use this technique: https://qiita.com/yuppe-namura/items/e72233fce89f1af2992d

You might want to translate it and see if there's useful information in there.

django-structlog is only a wrapper between django and structlog.
