### ISSUE TITLE
All error responses besides 404 get printed as a 500

### ISSUE THREAD

**Issue by shepdelacreme** [jrobichaud/django-structlog#61]
Should this handle other non-fatal errors similarly? e.g. 403, 400, etc? Right now this middleware logs an error with `code=500` for PermissionDenied (403) and other responses, which is not ideal.

https://github.com/jrobichaud/django-structlog/blob/1b4849039ee92688b53c502853a152c78a2dfe51/django_structlog/middlewares/request.py#L77-L93

**Comment by rabbit-aaron** [comment]
> Can provide the list of the middlewares in settings.py of your project?

I think if you create a view and raise `django.core.exceptions.PermissionDenied`
and it will be logged as 500

**Comment by jrobichaud** [comment]
Fixed in 2.1.2
