### ISSUE TITLE
Celery Task throws option is ignored by receiver_task_failure signal.

### ISSUE THREAD

**Issue by meunomemauricio** [jrobichaud/django-structlog#62]
In Celery, it's possible to specify a tuple of exceptions in the [throws](https://docs.celeryproject.org/en/stable/userguide/tasks.html#Task.throws) option. This allows us to mark a task as Failed but only log it as `INFO`, not `ERROR`.

This is how it's handled on Celery:

https://github.com/celery/celery/blob/1c955bf76a9a33052d87f2bccf0889fb21f27d41/celery/app/trace.py#L131-L141

https://github.com/celery/celery/blob/1c955bf76a9a33052d87f2bccf0889fb21f27d41/celery/app/trace.py#L233-L258

But this functionality is being ignored in the `receiver_task_failure` signal, which always log it as an exception:

https://github.com/jrobichaud/django-structlog/blob/1b4849039ee92688b53c502853a152c78a2dfe51/django_structlog/celery/receivers.py#L58-L61

I wonder if there's a way to work around this. I really like the `throws` functionality.

**Comment by jrobichaud** [comment]
Fixed in 2.1.3. Let me know if it does now suit your needs. 

I did like in Celery's documentation: Log as info and no traceback.
