### ISSUE TITLE
Remove quotes with flatline

### ISSUE THREAD

**Issue by CarlosLVar** [jrobichaud/django-structlog#63]
Hi there, I'm using a logfmt parser and for some reason it hates the single quotes around level='info' and such, is there an easy way to remove them?

Regards!

**Comment by jrobichaud** [comment]
@CarlosLVar I think your question relates more structlog than django-structlog. This is mostly a wrapper.

**Comment by CarlosLVar** [comment]
@jrobichaud Oh, thanks, I'll ask around there, sorry for the noise!
