### ISSUE TITLE
Naive Q: context variable vs thread local

### ISSUE THREAD

**Issue by james-certn** [jrobichaud/django-structlog#64]
The future is `contextvars` rather than `threadlocal`, isn't it? Is there a path to using context variables in place of thread locals for this project? Thank you!

**Comment by jrobichaud** [comment]
I’ll have to take a look at this. We have to keep backward compatibility.

Some help would be appreciated.

**Comment by jrobichaud** [comment]
Reference: https://www.structlog.org/en/stable/contextvars.html
