### ISSUE TITLE
Support `got_request_exception` signal and rely on it rather than on `process_exception` code

### ISSUE THREAD

**Issue by sshishov** [jrobichaud/django-structlog#658]
Hi dear maintainer

We are using `drf_standardized_errors` and this package is handling unhandled exception without propagating them: https://github.com/ghazi-git/drf-standardized-errors/issues/91

I would like to ask if it is possible to add the support for such scenario?

There can be 2 scenarios:
- unhandled exceptions are propagated using standard django way and calling `process_exception` on middlewares (`got_request_exception` is emitted in this scenario as well)
- unhandled exception is "handled" by some package and wrapped to return 500 and the signal `got_request_exception` is emitted.

Could we support both these scenarios as relying on `signal` which is used by Sentry as well is much more reliable than on middleware code which can be not called if exception is handled manually.

Best regards,
    Sergei

**Comment by jrobichaud** [comment]
Did you try to change the order of the middlewares in your `settings.py`?

In which order are you using them?

**Comment by jrobichaud** [comment]
@sshishov please try `9.0.0.dev2` and see #705.

https://pypi.org/project/django-structlog/9.0.0.dev2/

**Comment by sshishov** [comment]
Thanks @jrobichaud for the changes! 🎉 

We are about to upgrade `django-structlog` package now in our codebase. I will let you know how it is going...
I guess along with upgrade I will have to change our internal "handling" as I have added some "workaround" code before...

Cheers!

**Comment by jrobichaud** [comment]
Please let me know how it went.
