### ISSUE TITLE
Bump structlog to latest version

### ISSUE THREAD

**Issue by corno93** [jrobichaud/django-structlog#77]
I'd like to use the latest `structlog` version 21.5.0 as it comes with some new goodies such as these processors: `structlog.processors.CallsiteParameterAdder` and `structlog.stdlib.ExtraAdder`.

I'm wondering why in your setup you have not pinned `structlog` whereas in the requirements (`ci.txt`, `local-base.txt`) you have pinned it to `structlog>=19.2.0,<20`? I've bumped it locally and everything seems fine, however I thought i'd reach out to you in case there are some compatibility issues your aware of.

If there are no issues, in your CI could we run it with the latest `structlog` ?

**Comment by jrobichaud** [comment]
There are no compatibility issues that I am aware of.

There is the pending merge request #76 that will bump the CI along with breaking changes to support new features.

**Comment by corno93** [comment]
Sorry for the delayed reply, awesome!

Love your work btw, thanks a lot!

**Comment by jrobichaud** [comment]
Thanks! 
The changes I was referring to is not yet merged into master. The new PR is #78
